language: r
sudo: required
cache: packages
warnings_are_errors: false

global:
  - R_CHECK_ARGS="--no-build-vignettes --no-examples --no-manual"
  
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
